// Predefined architecture templates
export const DIAGRAM_TEMPLATES = [
  {
    id: 'serverless_web',
    name: 'Architettura Web Serverless',
    description: 'Frontend statico + API serverless + DB NoSQL su AWS',
    provider: 'aws',
    icon: '🌐',
    diagram: {
      nodes: [
        { id: 't_n0', serviceId: 'aws_cloudfront', x: 60, y: 220 },
        { id: 't_n1', serviceId: 'aws_s3', x: 240, y: 120 },
        { id: 't_n2', serviceId: 'aws_waf', x: 240, y: 320 },
        { id: 't_n3', serviceId: 'aws_api_gateway', x: 440, y: 220 },
        { id: 't_n4', serviceId: 'aws_cognito', x: 440, y: 380 },
        { id: 't_n5', serviceId: 'aws_lambda', x: 640, y: 220 },
        { id: 't_n6', serviceId: 'aws_dynamodb', x: 840, y: 140 },
        { id: 't_n7', serviceId: 'aws_elasticache', x: 840, y: 300 },
        { id: 't_n8', serviceId: 'aws_cloudwatch', x: 840, y: 440 },
      ],
      arrows: [
        { id: 't_a0', from: 't_n0', to: 't_n1' },
        { id: 't_a1', from: 't_n0', to: 't_n2' },
        { id: 't_a2', from: 't_n2', to: 't_n3' },
        { id: 't_a3', from: 't_n3', to: 't_n4' },
        { id: 't_a4', from: 't_n3', to: 't_n5' },
        { id: 't_a5', from: 't_n5', to: 't_n6' },
        { id: 't_a6', from: 't_n5', to: 't_n7' },
        { id: 't_a7', from: 't_n5', to: 't_n8' },
      ],
      groups: [
        { id: 't_g0', label: 'VPC AWS', x: 400, y: 80, width: 560, height: 420, color: '#F97316' },
      ],
    },
  },
  {
    id: 'data_pipeline',
    name: 'Data Pipeline Real-Time',
    description: 'Ingestion → Processing → Storage → Analytics su AWS',
    provider: 'aws',
    icon: '📊',
    diagram: {
      nodes: [
        { id: 't_n0', serviceId: 'aws_kinesis', x: 60, y: 220 },
        { id: 't_n1', serviceId: 'aws_lambda', x: 280, y: 220 },
        { id: 't_n2', serviceId: 'aws_s3', x: 500, y: 120 },
        { id: 't_n3', serviceId: 'aws_dynamodb', x: 500, y: 320 },
        { id: 't_n4', serviceId: 'aws_glue', x: 720, y: 120 },
        { id: 't_n5', serviceId: 'aws_opensearch', x: 720, y: 320 },
        { id: 't_n6', serviceId: 'aws_cloudwatch', x: 940, y: 220 },
      ],
      arrows: [
        { id: 't_a0', from: 't_n0', to: 't_n1' },
        { id: 't_a1', from: 't_n1', to: 't_n2' },
        { id: 't_a2', from: 't_n1', to: 't_n3' },
        { id: 't_a3', from: 't_n2', to: 't_n4' },
        { id: 't_a4', from: 't_n3', to: 't_n5' },
        { id: 't_a5', from: 't_n4', to: 't_n6' },
        { id: 't_a6', from: 't_n5', to: 't_n6' },
      ],
      groups: [],
    },
  },
  {
    id: 'rag_ai',
    name: 'Sistema RAG con AI',
    description: 'Retrieval Augmented Generation con Bedrock e knowledge base',
    provider: 'aws',
    icon: '🧠',
    diagram: {
      nodes: [
        { id: 't_n0', serviceId: 'aws_api_gateway', x: 60, y: 220 },
        { id: 't_n1', serviceId: 'aws_cognito', x: 60, y: 380 },
        { id: 't_n2', serviceId: 'aws_lambda', x: 280, y: 220 },
        { id: 't_n3', serviceId: 'aws_bedrock', x: 500, y: 140 },
        { id: 't_n4', serviceId: 'aws_bedrock_kb', x: 500, y: 300 },
        { id: 't_n5', serviceId: 'aws_s3', x: 720, y: 300 },
        { id: 't_n6', serviceId: 'aws_textract', x: 720, y: 440 },
        { id: 't_n7', serviceId: 'aws_cloudwatch', x: 940, y: 220 },
        { id: 't_n8', serviceId: 'aws_secrets_manager', x: 280, y: 400 },
      ],
      arrows: [
        { id: 't_a0', from: 't_n0', to: 't_n1' },
        { id: 't_a1', from: 't_n0', to: 't_n2' },
        { id: 't_a2', from: 't_n2', to: 't_n3' },
        { id: 't_a3', from: 't_n2', to: 't_n4' },
        { id: 't_a4', from: 't_n4', to: 't_n5' },
        { id: 't_a5', from: 't_n5', to: 't_n6' },
        { id: 't_a6', from: 't_n3', to: 't_n7' },
        { id: 't_a7', from: 't_n2', to: 't_n8' },
      ],
      groups: [
        { id: 't_g0', label: 'VPC Privata', x: 240, y: 80, width: 560, height: 440, color: '#8B5CF6' },
      ],
    },
  },
  {
    id: 'microservices_azure',
    name: 'Microservizi su Azure',
    description: 'Event-driven microservices con Azure Functions, Event Hubs e Cosmos DB',
    provider: 'azure',
    icon: '⚙️',
    diagram: {
      nodes: [
        { id: 't_n0', serviceId: 'az_api_management', x: 60, y: 220 },
        { id: 't_n1', serviceId: 'az_event_hubs', x: 280, y: 220 },
        { id: 't_n2', serviceId: 'az_functions', x: 500, y: 120 },
        { id: 't_n3', serviceId: 'az_functions', x: 500, y: 320 },
        { id: 't_n4', serviceId: 'az_cosmos_db', x: 720, y: 220 },
        { id: 't_n5', serviceId: 'az_service_bus', x: 500, y: 460 },
        { id: 't_n6', serviceId: 'az_monitor', x: 940, y: 220 },
        { id: 't_n7', serviceId: 'az_blob_storage', x: 720, y: 420 },
      ],
      arrows: [
        { id: 't_a0', from: 't_n0', to: 't_n1' },
        { id: 't_a1', from: 't_n1', to: 't_n2' },
        { id: 't_a2', from: 't_n1', to: 't_n3' },
        { id: 't_a3', from: 't_n2', to: 't_n4' },
        { id: 't_a4', from: 't_n3', to: 't_n4' },
        { id: 't_a5', from: 't_n3', to: 't_n5' },
        { id: 't_a6', from: 't_n4', to: 't_n6' },
        { id: 't_a7', from: 't_n5', to: 't_n7' },
      ],
      groups: [],
    },
  },
  {
    id: 'gcp_ml_platform',
    name: 'ML Platform su GCP',
    description: 'Training e serving modelli ML con Vertex AI e BigQuery',
    provider: 'gcp',
    icon: '🤖',
    diagram: {
      nodes: [
        { id: 't_n0', serviceId: 'gcp_pubsub', x: 60, y: 220 },
        { id: 't_n1', serviceId: 'gcp_storage', x: 280, y: 120 },
        { id: 't_n2', serviceId: 'gcp_bigquery', x: 280, y: 320 },
        { id: 't_n3', serviceId: 'gcp_vertex_ai', x: 500, y: 220 },
        { id: 't_n4', serviceId: 'gcp_run', x: 720, y: 220 },
        { id: 't_n5', serviceId: 'gcp_apigee', x: 940, y: 220 },
        { id: 't_n6', serviceId: 'gcp_monitoring', x: 720, y: 420 },
      ],
      arrows: [
        { id: 't_a0', from: 't_n0', to: 't_n1' },
        { id: 't_a1', from: 't_n0', to: 't_n2' },
        { id: 't_a2', from: 't_n1', to: 't_n3' },
        { id: 't_a3', from: 't_n2', to: 't_n3' },
        { id: 't_a4', from: 't_n3', to: 't_n4' },
        { id: 't_a5', from: 't_n4', to: 't_n5' },
        { id: 't_a6', from: 't_n4', to: 't_n6' },
      ],
      groups: [],
    },
  },
  {
    id: 'event_driven',
    name: 'Architettura Event-Driven',
    description: 'Flusso asincrono con SQS, SNS, Step Functions su AWS',
    provider: 'aws',
    icon: '⚡',
    diagram: {
      nodes: [
        { id: 't_n0', serviceId: 'aws_api_gateway', x: 60, y: 260 },
        { id: 't_n1', serviceId: 'aws_lambda', x: 280, y: 260 },
        { id: 't_n2', serviceId: 'aws_sns', x: 500, y: 160 },
        { id: 't_n3', serviceId: 'aws_sqs', x: 500, y: 360 },
        { id: 't_n4', serviceId: 'aws_step_functions', x: 720, y: 260 },
        { id: 't_n5', serviceId: 'aws_lambda', x: 940, y: 160 },
        { id: 't_n6', serviceId: 'aws_dynamodb', x: 940, y: 360 },
        { id: 't_n7', serviceId: 'aws_cloudwatch', x: 1160, y: 260 },
      ],
      arrows: [
        { id: 't_a0', from: 't_n0', to: 't_n1' },
        { id: 't_a1', from: 't_n1', to: 't_n2' },
        { id: 't_a2', from: 't_n1', to: 't_n3' },
        { id: 't_a3', from: 't_n2', to: 't_n4' },
        { id: 't_a4', from: 't_n3', to: 't_n4' },
        { id: 't_a5', from: 't_n4', to: 't_n5' },
        { id: 't_a6', from: 't_n4', to: 't_n6' },
        { id: 't_a7', from: 't_n5', to: 't_n7' },
      ],
      groups: [],
    },
  },
];

export const PROVIDER_COLORS = {
  aws: 'text-orange-400 bg-orange-500/10 border-orange-500/20',
  azure: 'text-blue-400 bg-blue-500/10 border-blue-500/20',
  gcp: 'text-green-400 bg-green-500/10 border-green-500/20',
};