// Full service library with visual metadata
export const SERVICE_LIBRARY = {
  // ── AWS ──────────────────────────────────────────────────────────────
  aws_route53: {
    id: 'aws_route53', provider: 'aws', category: 'networking',
    name: 'Route 53', fullName: 'AWS Route 53',
    description: 'DNS scalabile e registro domini globale. Instrada il traffico degli utenti alle applicazioni AWS.',
    color: '#8B5CF6', bg: '#7C3AED',
    icon: '53', iconType: 'text',
  },
  aws_waf: {
    id: 'aws_waf', provider: 'aws', category: 'security',
    name: 'WAF', fullName: 'AWS WAF',
    description: 'Web Application Firewall che protegge le applicazioni da exploit e bot web comuni.',
    color: '#EF4444', bg: '#DC2626',
    icon: '🔥', iconType: 'emoji',
  },
  aws_api_gateway: {
    id: 'aws_api_gateway', provider: 'aws', category: 'integration',
    name: 'API Gateway', fullName: 'AWS API Gateway',
    description: 'Crea, pubblica, mantiene e protegge API REST, HTTP e WebSocket a qualsiasi scala.',
    color: '#8B5CF6', bg: '#7C3AED',
    icon: '</>', iconType: 'text',
  },
  aws_lambda: {
    id: 'aws_lambda', provider: 'aws', category: 'compute',
    name: 'Lambda', fullName: 'AWS Lambda',
    description: 'Compute serverless che esegue codice senza provisioning o gestione di server. Scala automaticamente.',
    color: '#F97316', bg: '#EA580C',
    icon: 'λ', iconType: 'text',
  },
  aws_vpc_endpoint: {
    id: 'aws_vpc_endpoint', provider: 'aws', category: 'networking',
    name: 'VPC Endpoint', fullName: 'VPC Endpoints',
    description: 'Connessione privata tra VPC e servizi AWS senza traffico attraverso internet pubblico.',
    color: '#8B5CF6', bg: '#6D28D9',
    icon: '⊕', iconType: 'text',
  },
  aws_cloudwatch: {
    id: 'aws_cloudwatch', provider: 'aws', category: 'monitoring',
    name: 'CloudWatch', fullName: 'AWS CloudWatch',
    description: 'Monitoraggio e osservabilità per risorse e applicazioni AWS. Metriche, log e allarmi.',
    color: '#EC4899', bg: '#DB2777',
    icon: '☁', iconType: 'text',
  },
  aws_textract: {
    id: 'aws_textract', provider: 'aws', category: 'ai_ml',
    name: 'Textract', fullName: 'AWS Textract',
    description: 'Estrazione automatica di testo e dati da documenti scansionati usando ML.',
    color: '#0891B2', bg: '#0E7490',
    icon: '📄', iconType: 'emoji',
  },
  aws_rekognition: {
    id: 'aws_rekognition', provider: 'aws', category: 'ai_ml',
    name: 'Rekognition', fullName: 'AWS Rekognition',
    description: 'Analisi di immagini e video con ML. Rilevamento oggetti, volti, testo e contenuti inappropriati.',
    color: '#0891B2', bg: '#0E7490',
    icon: '🔍', iconType: 'emoji',
  },
  aws_bedrock: {
    id: 'aws_bedrock', provider: 'aws', category: 'ai_ml',
    name: 'Bedrock', fullName: 'AWS Bedrock',
    description: 'Accesso ai Foundation Models di AI tramite API. Claude, Llama, Titan e altri modelli generativi.',
    color: '#0891B2', bg: '#0E7490',
    icon: '🧠', iconType: 'emoji',
  },
  aws_bedrock_kb: {
    id: 'aws_bedrock_kb', provider: 'aws', category: 'ai_ml',
    name: 'Bedrock KB', fullName: 'AWS Bedrock Knowledge Base',
    description: 'Knowledge Base per RAG (Retrieval Augmented Generation) con connessione a fonti dati strutturate.',
    color: '#1E3A5F', bg: '#1E40AF',
    icon: '📚', iconType: 'emoji',
  },
  aws_s3: {
    id: 'aws_s3', provider: 'aws', category: 'storage',
    name: 'S3', fullName: 'AWS S3',
    description: 'Object storage con durabilità 99.999999999%. Archivia e recupera qualsiasi quantità di dati.',
    color: '#16A34A', bg: '#15803D',
    icon: '🪣', iconType: 'emoji',
  },
  aws_dynamodb: {
    id: 'aws_dynamodb', provider: 'aws', category: 'database',
    name: 'DynamoDB', fullName: 'AWS DynamoDB',
    description: 'Database NoSQL serverless con prestazioni a singola cifra millisecondo a qualsiasi scala.',
    color: '#2563EB', bg: '#1D4ED8',
    icon: 'DB', iconType: 'text',
  },
  aws_kinesis: {
    id: 'aws_kinesis', provider: 'aws', category: 'analytics',
    name: 'Kinesis', fullName: 'AWS Kinesis',
    description: 'Raccolta, elaborazione e analisi di dati di streaming in tempo reale.',
    color: '#7C3AED', bg: '#6D28D9',
    icon: '≋', iconType: 'text',
  },
  aws_sqs: {
    id: 'aws_sqs', provider: 'aws', category: 'integration',
    name: 'SQS', fullName: 'AWS SQS',
    description: 'Coda di messaggi completamente gestita per disaccoppiare microservizi e sistemi distribuiti.',
    color: '#DC2626', bg: '#B91C1C',
    icon: '◫', iconType: 'text',
  },
  aws_sns: {
    id: 'aws_sns', provider: 'aws', category: 'integration',
    name: 'SNS', fullName: 'AWS SNS',
    description: 'Servizio di notifica pub/sub completamente gestito per applicazioni distribuite.',
    color: '#DC2626', bg: '#B91C1C',
    icon: '🔔', iconType: 'emoji',
  },
  aws_ecs: {
    id: 'aws_ecs', provider: 'aws', category: 'compute',
    name: 'ECS', fullName: 'AWS ECS',
    description: 'Servizio di orchestrazione container completamente gestito. Esegui container Docker in produzione.',
    color: '#F97316', bg: '#EA580C',
    icon: '⬡', iconType: 'text',
  },
  aws_eks: {
    id: 'aws_eks', provider: 'aws', category: 'compute',
    name: 'EKS', fullName: 'AWS EKS',
    description: 'Kubernetes gestito su AWS. Esegui e scala applicazioni containerizzate con Kubernetes.',
    color: '#F97316', bg: '#EA580C',
    icon: 'K8s', iconType: 'text',
  },
  aws_rds: {
    id: 'aws_rds', provider: 'aws', category: 'database',
    name: 'RDS', fullName: 'AWS RDS',
    description: 'Database relazionale gestito. Supporta MySQL, PostgreSQL, Oracle, SQL Server, MariaDB.',
    color: '#2563EB', bg: '#1D4ED8',
    icon: '⚙', iconType: 'text',
  },
  aws_elasticache: {
    id: 'aws_elasticache', provider: 'aws', category: 'database',
    name: 'ElastiCache', fullName: 'AWS ElastiCache',
    description: 'Cache in-memory gestita con Redis o Memcached per prestazioni ultra-rapide.',
    color: '#DC2626', bg: '#B91C1C',
    icon: '⚡', iconType: 'text',
  },
  aws_cloudfront: {
    id: 'aws_cloudfront', provider: 'aws', category: 'networking',
    name: 'CloudFront', fullName: 'AWS CloudFront',
    description: 'CDN globale per distribuzione rapida di contenuti statici e dinamici con bassa latenza.',
    color: '#8B5CF6', bg: '#7C3AED',
    icon: '◎', iconType: 'text',
  },
  aws_cognito: {
    id: 'aws_cognito', provider: 'aws', category: 'security',
    name: 'Cognito', fullName: 'AWS Cognito',
    description: 'Autenticazione, autorizzazione e gestione utenti per app web e mobile.',
    color: '#DC2626', bg: '#B91C1C',
    icon: '👤', iconType: 'emoji',
  },
  aws_secrets_manager: {
    id: 'aws_secrets_manager', provider: 'aws', category: 'security',
    name: 'Secrets Manager', fullName: 'AWS Secrets Manager',
    description: 'Rotazione, gestione e recupero sicuro di credenziali, API key e secrets.',
    color: '#DC2626', bg: '#B91C1C',
    icon: '🔐', iconType: 'emoji',
  },
  aws_step_functions: {
    id: 'aws_step_functions', provider: 'aws', category: 'integration',
    name: 'Step Functions', fullName: 'AWS Step Functions',
    description: 'Orchestrazione serverless di workflow. Coordina servizi AWS in sequenze visive.',
    color: '#EC4899', bg: '#DB2777',
    icon: '⊞', iconType: 'text',
  },
  aws_glue: {
    id: 'aws_glue', provider: 'aws', category: 'analytics',
    name: 'Glue', fullName: 'AWS Glue',
    description: 'ETL serverless e integrazione dati. Prepara e trasforma dati per analytics e ML.',
    color: '#7C3AED', bg: '#6D28D9',
    icon: '◈', iconType: 'text',
  },
  aws_opensearch: {
    id: 'aws_opensearch', provider: 'aws', category: 'analytics',
    name: 'OpenSearch', fullName: 'AWS OpenSearch',
    description: 'Ricerca full-text distribuita e analytics log in tempo reale. Fork di Elasticsearch.',
    color: '#0891B2', bg: '#0E7490',
    icon: '⌖', iconType: 'text',
  },

  // ── AZURE ────────────────────────────────────────────────────────────
  az_api_management: {
    id: 'az_api_management', provider: 'azure', category: 'integration',
    name: 'API Management', fullName: 'Azure API Management',
    description: 'Pubblica, proteggi e analizza API. Gateway ibrido per API cloud e on-premise.',
    color: '#2563EB', bg: '#1D4ED8',
    icon: '</>', iconType: 'text',
  },
  az_functions: {
    id: 'az_functions', provider: 'azure', category: 'compute',
    name: 'Functions', fullName: 'Azure Functions',
    description: 'Compute serverless event-driven. Esegui codice in risposta a trigger senza infrastruttura.',
    color: '#2563EB', bg: '#1D4ED8',
    icon: 'ƒ', iconType: 'text',
  },
  az_event_hubs: {
    id: 'az_event_hubs', provider: 'azure', category: 'integration',
    name: 'Event Hubs', fullName: 'Azure Event Hubs',
    description: 'Piattaforma Big Data streaming. Riceve milioni di eventi al secondo da app e device.',
    color: '#2563EB', bg: '#1D4ED8',
    icon: '⟳', iconType: 'text',
  },
  az_cosmos_db: {
    id: 'az_cosmos_db', provider: 'azure', category: 'database',
    name: 'Cosmos DB', fullName: 'Azure Cosmos DB',
    description: 'Database NoSQL distribuito globalmente con latenze < 10ms. Multi-modello.',
    color: '#2563EB', bg: '#1D4ED8',
    icon: '◉', iconType: 'text',
  },
  az_blob_storage: {
    id: 'az_blob_storage', provider: 'azure', category: 'storage',
    name: 'Blob Storage', fullName: 'Azure Blob Storage',
    description: 'Object storage massivamente scalabile per dati non strutturati. Ottimizzato per Big Data.',
    color: '#2563EB', bg: '#1D4ED8',
    icon: '🗄', iconType: 'emoji',
  },
  az_monitor: {
    id: 'az_monitor', provider: 'azure', category: 'monitoring',
    name: 'Monitor', fullName: 'Azure Monitor',
    description: 'Piattaforma completa per raccogliere, analizzare e agire su telemetria cloud e on-premise.',
    color: '#2563EB', bg: '#1D4ED8',
    icon: '📊', iconType: 'emoji',
  },
  az_openai: {
    id: 'az_openai', provider: 'azure', category: 'ai_ml',
    name: 'Azure OpenAI', fullName: 'Azure OpenAI Service',
    description: 'Accesso ai modelli OpenAI (GPT-4, DALL-E, Whisper) su infrastruttura Azure sicura.',
    color: '#16A34A', bg: '#15803D',
    icon: '🤖', iconType: 'emoji',
  },
  az_service_bus: {
    id: 'az_service_bus', provider: 'azure', category: 'integration',
    name: 'Service Bus', fullName: 'Azure Service Bus',
    description: 'Broker di messaggi enterprise per integrazione cloud affidabile e sicura.',
    color: '#2563EB', bg: '#1D4ED8',
    icon: '⇄', iconType: 'text',
  },
  az_aks: {
    id: 'az_aks', provider: 'azure', category: 'compute',
    name: 'AKS', fullName: 'Azure Kubernetes Service',
    description: 'Kubernetes gestito su Azure. Semplifica deployment e operazioni di cluster K8s.',
    color: '#2563EB', bg: '#1D4ED8',
    icon: 'K8s', iconType: 'text',
  },

  // ── GCP ──────────────────────────────────────────────────────────────
  gcp_pubsub: {
    id: 'gcp_pubsub', provider: 'gcp', category: 'integration',
    name: 'Pub/Sub', fullName: 'Google Cloud Pub/Sub',
    description: 'Messaggistica e streaming real-time. Pattern event-driven per sistemi distribuiti.',
    color: '#16A34A', bg: '#15803D',
    icon: '⊸', iconType: 'text',
  },
  gcp_functions: {
    id: 'gcp_functions', provider: 'gcp', category: 'compute',
    name: 'Cloud Functions', fullName: 'Google Cloud Functions',
    description: 'Funzioni serverless event-driven. Scala automaticamente da zero a milioni di richieste.',
    color: '#16A34A', bg: '#15803D',
    icon: 'ƒ', iconType: 'text',
  },
  gcp_firestore: {
    id: 'gcp_firestore', provider: 'gcp', category: 'database',
    name: 'Firestore', fullName: 'Google Firestore',
    description: 'Database documentale NoSQL serverless con sync in tempo reale.',
    color: '#F97316', bg: '#EA580C',
    icon: '🔥', iconType: 'emoji',
  },
  gcp_storage: {
    id: 'gcp_storage', provider: 'gcp', category: 'storage',
    name: 'Cloud Storage', fullName: 'Google Cloud Storage',
    description: 'Object storage unificato. Classi automatiche per ottimizzare costi in base all\'accesso.',
    color: '#16A34A', bg: '#15803D',
    icon: '🪣', iconType: 'emoji',
  },
  gcp_bigquery: {
    id: 'gcp_bigquery', provider: 'gcp', category: 'analytics',
    name: 'BigQuery', fullName: 'Google BigQuery',
    description: 'Data warehouse serverless e analytics engine. Analisi SQL su petabyte in secondi.',
    color: '#2563EB', bg: '#1D4ED8',
    icon: '◧', iconType: 'text',
  },
  gcp_apigee: {
    id: 'gcp_apigee', provider: 'gcp', category: 'integration',
    name: 'Apigee', fullName: 'Google Apigee',
    description: 'Piattaforma API management per progettare, proteggere, analizzare e scalare API.',
    color: '#16A34A', bg: '#15803D',
    icon: '</>', iconType: 'text',
  },
  gcp_vertex_ai: {
    id: 'gcp_vertex_ai', provider: 'gcp', category: 'ai_ml',
    name: 'Vertex AI', fullName: 'Google Vertex AI',
    description: 'Piattaforma ML unificata per training, deploy e gestione modelli AI a scala.',
    color: '#2563EB', bg: '#1D4ED8',
    icon: '🧠', iconType: 'emoji',
  },
  gcp_run: {
    id: 'gcp_run', provider: 'gcp', category: 'compute',
    name: 'Cloud Run', fullName: 'Google Cloud Run',
    description: 'Container serverless. Deploy immediato con autoscaling a zero. Nessuna infrastruttura.',
    color: '#16A34A', bg: '#15803D',
    icon: '▷', iconType: 'text',
  },
  gcp_monitoring: {
    id: 'gcp_monitoring', provider: 'gcp', category: 'monitoring',
    name: 'Cloud Monitoring', fullName: 'Google Cloud Monitoring',
    description: 'Visibilità su performance, uptime e salute dei servizi GCP, AWS e ibridi.',
    color: '#16A34A', bg: '#15803D',
    icon: '📈', iconType: 'emoji',
  },
};

export const CATEGORIES = {
  networking: { label: 'Networking', color: '#8B5CF6' },
  security: { label: 'Sicurezza', color: '#EF4444' },
  compute: { label: 'Compute', color: '#F97316' },
  integration: { label: 'Integrazione', color: '#7C3AED' },
  storage: { label: 'Storage', color: '#16A34A' },
  database: { label: 'Database', color: '#2563EB' },
  analytics: { label: 'Analytics', color: '#0891B2' },
  ai_ml: { label: 'AI / ML', color: '#0891B2' },
  monitoring: { label: 'Monitoring', color: '#EC4899' },
};

export const PROVIDERS = {
  aws: { label: 'AWS', color: '#F97316', textColor: 'text-orange-400' },
  azure: { label: 'Azure', color: '#2563EB', textColor: 'text-blue-400' },
  gcp: { label: 'GCP', color: '#16A34A', textColor: 'text-green-400' },
};

export function getServicesByProvider(provider) {
  return Object.values(SERVICE_LIBRARY).filter(s => s.provider === provider);
}

export function getServicesByCategory(category) {
  return Object.values(SERVICE_LIBRARY).filter(s => s.category === category);
}